services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.35.0
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002

  ready:
    image: andrewlock/wait-for-dependencies
    command: azurite:10000
    depends_on:
      - azurite


